# Generated by Django 6.0.3 on 2026-04-08 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="social_provider",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_uid",
        ),
    ]
