# Generated by Django 6.0.3 on 2026-04-08 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_social_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
    ]
