# Generated by Django 6.0.3 on 2026-04-08 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "입금"), ("withdrawal", "출금")],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "식비"),
                            ("transport", "교통비"),
                            ("fixed", "고정비용"),
                            ("savings", "저축"),
                            ("living", "생활비"),
                            ("culture", "문화생활"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("transacted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
